services:
  - type: web
    name: n8n
    env: docker
    image: n8nio/n8n:latest     # koristi oficijelni image; ukloni dockerfilePath
    plan: standard              # ili "starter" ako želiš jeftinije
    autoDeploy: true
    envVars:
      - key: N8N_ENCRYPTION_KEY
        value: "CHANGE_ME_32CHARS_MIN"
      - key: N8N_HOST
        value: "your-subdomain.onrender.com"
      - key: N8N_PROTOCOL
        value: "https"
      - key: WEBHOOK_URL
        value: "https://your-subdomain.onrender.com/"
      - key: N8N_DATABASE_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_SSL
        value: "true"

databases:
  - name: n8n-db
    plan: starter
